### ISSUE TITLE
Schedule endpoints logging error that is associated w/ Rise Player (error 27)

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-image#102]
9814 non display endpoints are logging, "Rise Player encountered a problem saving the file" - error 23. Once the underlying cause is confirmed, image component should be updated to log an error code that  adheres to the uptime error standards. 

The error currently being is not actionable and it error 23 is associated with Rise Player which is not present in shared schedules.

**Comment by stulees** [comment]
@alanclayton I think the error code you're referring to is `E000000027`, not `E000000023`. @olegrise @santiagonoguez FYI

**Comment by alanclayton** [comment]
@stulees You're correct. It is 27, not 23.

**Comment by tejohnso** [comment]
In addition to associating with Rise Player, the log frequency is insane.

This query shows at least one endpoint logging the same E000000027 error hundreds of times per second.
 
```
select * from `endpoint-event-logs.logs.eventLog` where 
date(timestamp) = "2021-04-26"
and endpointId = "ac1ac885ec08b63284c7e10b33a14120"
order by timestamp desc
```

**Comment by stulees** [comment]
@tejohnso Thanks. We are prioritizing investigation into this today. We'll hopefully understand the situation better later today. @olegrise @santiagonoguez FYI

**Comment by olegrise** [comment]
@stulees @santiagonoguez @tejohnso I think I was able to reproduce it. Watch the [video](https://drive.google.com/file/d/1fqyZoNOg-_n_uS4D1H5DolCKk2Z5crnX/view?usp=sharing).

**Comment by tejohnso** [comment]
@santiagonoguez this could be the scenario we saw earlier and were discussing today where the version [returned in the response header](https://github.com/Rise-Vision/content-sentinel/blob/master/src/fetcher.js#L19) does not match the version on MS and so the file goes [right back into the queue](https://github.com/Rise-Vision/content-sentinel/blob/master/src/download-queue.js#L34) since the version mismatch results in STALE status.

When we first saw it the cause was the bucket on GCS was not configured to receive update notifications, which can be checked with gsutil (eg `gsutil notification list gs://risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4`)

I think we should try to reproduce this on production viewer, with production schedules and production buckets. We might also want to reconsider that re-queueing logic.

@olegrise @stulees fyi
