### ISSUE TITLE
Endpoints are not showing an image or video because of a failure to retrieve it

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-image#117]
### Problem to be solved.
Our logs are reporting that 3,800 endpoints are not showing an image or video because of a failure to retrieve it.
Error E000000215 is logged with non meaningful eventDetails and miscellaneous debugInfo. Some of them seem to be related to ‘cancelled’ downloads. Most likely the user navigated away from the page and in this case it should not log an uptime error. 
We don’t have an understanding of the other failures, so we need better eventDetails information to decide how we can fix the errors.

### What is the expected behavior from the user’s point of view?
All images and videos are successfully retrieved and shown in the templates.
Any files that failed to download are logged with informative eventDetails, and legit cancelled downloads are not logged as uptime failures.

### What is the actual behavior from the user’s point of view?
One or more images or videos are failing to be shown in a presentation due to a failure to retrieve them.

**Comment by olegrise** [comment]
@ezequielc the error E000000215 logged by our components is simply a mirror of the error in the Common Sentinel.  As you can see [here](https://github.com/Rise-Vision/content-sentinel/blob/dfe4717be8f12d2e181f4061f2b6cebf54bda8ef/src/download-queue.js#L135-L142) the Common Sentinel notifies component about an error and then logs that error as well.

Considering that the error originates in the Common Sentinel, it would be more productive to do the investigation in the Common Sentinel itself. There is a better context of what is going on there and therefore more meaningful information can be added to the log details. I recommend this work is done by the Delivery team.

As for not logging an error in case when download is cancelled - makes sense. We just made this change in `rise-image` and `rise-video`, so this aspect of the issue is resolved.

**Comment by ezequielc** [comment]
@olegrise Thanks for the review and fixes. Delivery already made some improvements on Content Sentinel logging, so at this point we can monitor the results of that and your work. I am good with closing this. Thanks

**Comment by olegrise** [comment]
@ezequielc Thanks!
