### ISSUE TITLE
Done event is not sent when there is a Rise Local Storage file error

### ISSUE THREAD

**Issue by andrecardoso** [Rise-Vision/rise-image#37]
**How it Currently Works** 
When `rise-image` is configured with `play-until-done` and RLS sends an error message, for instance when there's insufficient disk space, the `done` event is not sent and the template might get stuck

**How it Should Work** 

`rise-image` should send the `done` event if it can't render because there's an RLS error

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [rise-image #37] Done event is not sent when there is a Rise Local Storage file error](https://trello.com/c/n7IEWilo/216-2-rise-image-37-done-event-is-not-sent-when-there-is-a-rise-local-storage-file-error)

**Comment by olegrise** [comment]
@Stuart Lees I've noticed that when file does not exist in the Storage (status = `NOEXIST`), then `rise-image` does not do anything. As a result the file doesn't end up neither in `_managedFiles` list nor in `_managedFilesInError`. This is a problem for PUD because it needs to know when all files loading is completed either successfully or unsuccessfully. For example if all requested images return `NOEXIST` status, then there is nothing to show and `rise-image` should send PUD event. 

**Do you think `NOEXIST` status should be treated the same way as `FILE-ERROR` [here](https://github.com/Rise-Vision/rise-image/blob/master/src/rise-image.js#L595)?** The reason I ask is because `_manageFileInError()` method also [logs an error in BQ](https://github.com/Rise-Vision/rise-image/blob/master/src/rise-image.js#L567) and it's probably going to impact `rise-image` reliability. I'm not sure if that's what we want to do in this case. @santiagonoguez FYI.

BTW, it looks like former `image-widget` component handles `NOEXIST` status correctly and [logs an error](https://github.com/Rise-Vision/widget-image/blob/38f53262396c8c0c49e2a186b1ad7688932f61f2/src/widget/player-local-storage-file.js#L116).

**Comment by santiagonoguez** [comment]
@olegrise @stulees another option could be keeping those files in a third list ( like _filesNotExist ), and let PUD also look there. Thoughts ?

**Comment by olegrise** [comment]
@santiagonoguez I would rather merge `_managedFiles` and `_manageFileInError` into one. The component already has 4 lists. Adding one more would just create more problems in my opinion.

**Comment by santiagonoguez** [comment]
@olegrise ok to me then, and maybe then just not sending to BQ if it's not really an error ( but a file that does no longer exist ). or send a warning in that case instead.

**Comment by santiagonoguez** [comment]
@willread we need to keep an eye on this fix, because it may also require similar changes for rise-video, thanks !

**Comment by stulees** [comment]
@olegrise Yes agreed on handling it as `FILE-ERROR` is  handled(logging to BQ), it's consistent with Image Widget as you pointed out. It's always helpful to know and react to this kind of thing for a users sake. Eventually we may want to downgrade to a warning, but lets see how this impacts first. Thanks for catching this 👍

**Comment by olegrise** [comment]
@stulees sounds good. Thanks.

**Comment by santiagonoguez** [comment]
@olegrise yesterday a "file-not-found" error showed for rise-image for the first time; curious if that's related to this fix.

**Comment by olegrise** [comment]
@santiagonoguez yes, I introduced that in the fix.

**Comment by santiagonoguez** [comment]
@olegrise nice, thanks ! @stulees FYI

**Comment by santiagonoguez** [comment]
@olegrise another question, curious, where's the code of that fix ?

**Comment by olegrise** [comment]
@santiagonoguez still on my local machine. I'm going to create a PR in about an hour.

**Comment by santiagonoguez** [comment]
@olegrise :D that explains why I couldn't find it !!!! :D :D :D

**Comment by olegrise** [comment]
Issue is fixed.

**Comment by santiagonoguez** [comment]
@olegrise thanks, we'll replicate this fix for video on this card:
https://trello.com/c/7dNtZgYT/7210-issue-replicate-rise-image-pud-fix-for-video-2
