### ISSUE TITLE
Uptime Error 200: Browser unable to render image

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-image#98]
**Current User Experience**
All the image files that I added to my presentation do not always show when they are supposed to. I don't know why this happens and I don't know how to fix this. 

**Expected User Experience**
Images added to a presentation show every time as expected without fail. 

**Technical Details**
From June 17 - June 23, 173 displays have reported uptime error 200. The display id's and debug info from dailyEvents can be found here, https://drive.google.com/file/d/1gvfTjWa5h5KDPS7ZSa3H6c0tgGTP_T66/view?usp=sharing

**Comment by olegrise** [comment]
### Update:
It seems that error 200 is mostly reported by legacy templates. Those templates still have their own service workers with a route for "widgets.risevision.com". The template's service workers intercept image and video requests and return 404 error. Example legacy "Wash Your Hands" template [here](https://console.cloud.google.com/storage/browser/widgets.risevision.com/stable/templates/83d1fdc6ac6120843d2d4342d9687895e284b81a;tab=objects?project=avid-life-623&prefix=&forceOnObjectsSortingFiltering=false).
@stulees @santiagonoguez

**Comment by tejohnso** [comment]
@olegrise can you take this given it's rise-image?
@santiagonoguez fyi

**Comment by olegrise** [comment]
**Update:**

The service workers in the legacy templates were renamed to `_service-worker.js` on GCS. That way a template can no longer load it. That solves the problem with Error 200.

Some technical details:
The reason some legacy templates in GCS were still using service workers in spite the fact that we updated all templates in GitHub is because those templates are orphan. A template becomes orphan when the template version or name changes and as a result product code changes and then the template destination folder in GCS changes as well.

**Comment by ByronDarlison** [comment]
@olegrise do these templates need to be manually updated to correct this problem? FYI @mmeiers Thanks

**Comment by olegrise** [comment]
@ByronDarlison we already manually corrected them and it solved the issue on affected displays. We still see the issue on ~120 displays most likely for a different reason. I'm investigating now. Thanks.

**Comment by ByronDarlison** [comment]
Thanks!

**Comment by stulees** [comment]
Closing this issue, history of investigation and analysis can be found [here](https://docs.google.com/document/d/1njpQARG4BskJcsCpgS2ob-emNqVlZmYeszCHavpmuoA/edit#bookmark=id.3w0r4bc04ps7)
